[project]
name        = "ComfyUI-Aiya-MMX"
version     = "1.0.0"
description = "ğŸ’• å“å‘€âœ¦MMX ç³»åˆ—é•œåƒèŠ‚ç‚¹ â€”â€” æ°´å° / å°ºå¯¸ / ä¿å­˜ / åˆ†è¾¨ç‡ä¸€é”®é­”æ³•"
readme      = "README.md"
license     = {file = "LICENSE"}
authors     = [
    {name = "MuAIGC", email = "hello@muai.gc"},
]
dependencies = [
    "torch",
    "torchvision",
    "opencv-python",
    "Pillow",
    "numpy",
]

[project.urls]
Repository    = "https://github.com/MuAIGC/ComfyUI-Aiya-MMX"

[tool.comfy]
PublisherId = "MuAIGC"
DisplayName = "ComfyUI-Aiya-MMX"
Icon        = "https://github.com/MuAIGC/ComfyUI-Aiya-MMX/blob/main/ComfyUI-Aiya-MMX-B.jpg"
